[build]
  command = "npm install vite && npm run build"
  publish = "dist"
  node_version = "18"

[build.environment]
  NODE_ENV = "production"
  NPM_FLAGS = "--legacy-peer-deps"

[functions]
  node_bundler = "esbuild"

[context.production.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
